--
-- PostgreSQL database dump
--

-- Dumped from database version 14.5
-- Dumped by pg_dump version 14.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: TotalItems; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA "TotalItems";


ALTER SCHEMA "TotalItems" OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: categories; Type: TABLE; Schema: TotalItems; Owner: postgres
--

CREATE TABLE "TotalItems".categories (
    id integer NOT NULL,
    parent integer
);


ALTER TABLE "TotalItems".categories OWNER TO postgres;

--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: TotalItems; Owner: postgres
--

ALTER TABLE "TotalItems".categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "TotalItems".categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: items; Type: TABLE; Schema: TotalItems; Owner: postgres
--

CREATE TABLE "TotalItems".items (
    id integer NOT NULL,
    category_id integer
);


ALTER TABLE "TotalItems".items OWNER TO postgres;

--
-- Name: items_id_seq; Type: SEQUENCE; Schema: TotalItems; Owner: postgres
--

ALTER TABLE "TotalItems".items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "TotalItems".items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: categories; Type: TABLE DATA; Schema: TotalItems; Owner: postgres
--

COPY "TotalItems".categories (id, parent) FROM stdin;
1	\N
2	1
3	1
4	2
5	2
6	3
7	3
8	3
9	4
10	4
11	4
12	4
13	6
14	6
15	8
16	8
17	8
18	8
19	8
20	17
21	17
22	20
23	20
24	\N
25	24
26	24
\.


--
-- Data for Name: items; Type: TABLE DATA; Schema: TotalItems; Owner: postgres
--

COPY "TotalItems".items (id, category_id) FROM stdin;
1	5
2	5
3	5
4	5
5	5
6	5
7	7
8	7
9	9
10	9
11	9
12	9
13	9
14	10
15	10
16	10
17	10
18	11
19	11
20	11
21	11
22	13
23	14
24	16
25	16
26	18
27	18
28	18
29	21
30	21
31	21
32	21
33	21
34	22
35	22
36	22
37	22
38	25
39	25
40	25
41	25
42	25
43	25
44	25
45	25
46	25
47	25
48	25
49	25
50	25
51	25
52	25
53	25
54	25
55	25
56	25
57	25
58	26
59	26
60	26
61	26
62	26
\.


--
-- Name: categories_id_seq; Type: SEQUENCE SET; Schema: TotalItems; Owner: postgres
--

SELECT pg_catalog.setval('"TotalItems".categories_id_seq', 1, false);


--
-- Name: items_id_seq; Type: SEQUENCE SET; Schema: TotalItems; Owner: postgres
--

SELECT pg_catalog.setval('"TotalItems".items_id_seq', 1, false);


--
-- PostgreSQL database dump complete
--

